name: Auto Tag on Commit

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git config
      run: |
        git config user.name "AasviGoswami"
        git config user.email "aasvigoswami0911@gmail.com"

    - name: Get current date and commit SHA
      id: vars
      run: |
        echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create tag
      run: |
        git tag "auto-${{ env.DATE }}-${{ env.SHA }}"
        git push origin --tags
