name: Automated Tagging

on:
  push:
    branches:
      - main  # Change to 'dev' if you want tagging on dev

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --local user.email "aasvigoswami0911@gmail.com"
          git config --local user.name "AasviGoswami"

      - name: Create Tag
        run: |
          git config --local user.email "aasvigoswami0911@gmail.com"
          git config --local user.name "AasviGoswami"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin "v${{ github.run_number }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release v${{ github.run_number }}"
          body: "Description of the changes in this release"
